### PR TITLE
add new msg MISSION_REQUEST_INT

### PR DESCRIPTION
**Pull request by meee1**

### CODE REVIEW

**Comment by m11s** [comment]
@tridge 
Could you merge this?
It's needed for progress with https://github.com/ArduPilot/ardupilot/pull/3688

**Comment by mr337** [comment]
Any update on this? Def looking at https://github.com/ArduPilot/ardupilot/pull/3688 getting merged soon :D

**Comment by WickedShell** [comment]
This is now in upstream.

**Comment by mr337** [comment]
woot!

**Pull request closed without merging**
