### PR TITLE
Ardupilot: Add a enum for mapping plane flight modes

### PR DESCRIPTION
**Pull request by WickedShell**
First step towards enumerating flight modes in a consistent fashion over mavlink. If everyone is fine with this format I can create copter/rover/tracker as well.

### CODE REVIEW

**Comment by magicrub** [comment]
I'd suggest renaming to PLANE_FLIGHT_MODE without the 'S' but otherwise LGTM.

**Comment by WickedShell** [comment]
Good point, updated

**Comment by magicrub** [comment]
This looks ready

**Comment by tridge** [comment]
the only problem I see with this is that if we use the enum attribute in HEARTBEAT then as that is in common.xml it will affect all projects, not just ArduPilot

**Comment by DonLakeFlyer** [comment]
> the only problem I see with this is that if we use the enum attribute in HEARTBEAT then as that is in common.xml it will affect all projects, not just ArduPilot

FYI: QGC is built with the ArduPilot dialect since that currently works for both ArduPIlot and PX4. So if the enum made it to heartbeat it would throw QGC out of whack a bit.

**Comment by WickedShell** [comment]
Sorry this wasn't really made clear here, I had discussed it with @tridge awhile ago, the only intention was to use this in the custom_mode field the same way we currently stick numbers in there. (And still set the custom mode flag the sameway)

**Comment by WickedShell** [comment]
Replaced by #61 which implemented all of the vehicles.

**Pull request closed without merging**
