### PR TITLE
ArduPilot: Add success/failure states to accel cal reporting

### PR DESCRIPTION
**Pull request by WickedShell**
For use with https://github.com/ArduPilot/ardupilot/pull/6341

~~I'm not sure why there are submodule changes... I need to double check that part, opening now for comments though.~~ EDIT: Fixed 

The values picked were the max integer values that can fit in a float correctly with 100% reliability. (Sticking with unsigned types minimized the changes in the accel cal lib)

### CODE REVIEW

**Comment by WickedShell** [comment]
I'm going to need some help sorting out why the Python3 builds are failing...

**Comment by WickedShell** [comment]
Not intended to be closed, reopened

**Comment by OXINARF** [comment]
@WickedShell Can you rebase this on master? Just trying to ensure CI is happy.

**Comment by WickedShell** [comment]
Rebased, CI is now happy

**Pull request merged**
