### PR TITLE
Add GENERATOR_STATUS message

### PR DESCRIPTION
**Pull request by peterbarker**
... I'll be creating a PR against mavlink upstream with proposed changes to this message.

### CODE REVIEW

**Comment by peterbarker** [comment]
PR against upstream: https://github.com/mavlink/mavlink/pull/1416

**Comment by peterbarker** [comment]
CI won't pass here until the pymavlink submodule is updated; a new unit "W" (Watts) has been added.

The upstream PR passes.

**Comment by rmackay9** [comment]
This seems reasonable to me.  I think there's no question that the first commit can go in.  For the follow-up changes, if we merge this before they are accepted upstream then we risk diverging on a message that we didn't create.

@amilcarlucas FYI

**Comment by rmackay9** [comment]
@tridge how do you feel about merging this?

**Comment by peterbarker** [comment]
Upstream accepted the rename and the new flags field - so everything this PR does.

**Comment by tridge** [comment]
looks good, but we still need a PR for Watts in pymavlink, right?

**Comment by peterbarker** [comment]
@tridge I've added a patch here to update the pymavlink reference to the 2.4.9 pymavlink release.

Doesn't seem to have triggered a CI run :-/

**Comment by peterbarker** [comment]
.... OK, so I've had to go to the master commit on pymavlink as it contains a CI fix.

**Comment by peterbarker** [comment]
@tridge CI has been fixed on this PR now.

**Pull request merged**
