### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by amilcarlucas**
Merge upstream updates from the mavlink/mavlink repository

### CODE REVIEW

**Comment by magicrub** [comment]
This is a major update, LOTS of changed. I see https://github.com/mavlink/mavlink/issues/780 so it would be good to confirm it compiles

**Comment by amilcarlucas** [comment]
That issue that you mention is not a real problem. The real problem IMHO is:
https://github.com/ArduPilot/mavlink/pull/52/commits/f3315b930529a43e9bbde6bf6050d4e79fbdae72

**Comment by amilcarlucas** [comment]
OK, I moved the intrusive upstream commits to #53 
This PR only contains mild changes :)

**Comment by amilcarlucas** [comment]
We do have our own build server, and it builds fine there. I also been flying with these code changes for a couple of days now. All is fine.

But our build server only does the SITL flight tests and the px2 and px3 builds. So I do not know if these will break the linux builds for instance :(

**Comment by amilcarlucas** [comment]
rebased and removed all the WIP commits

**Comment by amilcarlucas** [comment]
This requires ardupilot/#6987

**Comment by tridge** [comment]
thanks Amilcar, applied!

**Pull request merged**
