### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@tridge @peterbarker Can we please merge this? I don't have merge rights.

**Comment by tridge** [comment]
I'm not a fan of the addition of a '.' on all message descriptions, as it loses our git history, but I will merge to keep diffs to a minimum

**Comment by tridge** [comment]
@hamishwillee and @amilcarlucas thanks for all your work on this, even if I don't like the '.' :-)

**Comment by hamishwillee** [comment]
Hi @tridge, thanks for merging. Those are entirely my fault. I live for punctuation.

**Comment by hamishwillee** [comment]
@amilcarlucas Can you do another push now we've caught up. I need the recent description updates so that we can push in mandatory message descriptions: https://github.com/ArduPilot/pymavlink/pull/215

@tridge Clearly that was a pain to review and merge. Is there any specific testing or process (other than not doing ".") that will make this easier for you? Smaller/more regular PRs?

**Pull request merged**
