### PR TITLE
add vendor specs for cubepilot

### PR DESCRIPTION
**Pull request by bugobliterator**
These are some custom message sets that CubePilot have been using internally. Adding them to master will help streamline things for us.

### CODE REVIEW

**Comment by peterbarker** [comment]
Looks right to me - CI is a little peeved about the formatting, but the suggestion it makes does actually work to fix those problems.

Is there an upstream equivalent to this yet?

**Comment by bugobliterator** [comment]
> Looks right to me - CI is a little peeved about the formatting, but the suggestion it makes does actually work to fix those problems.
> 
> Is there an upstream equivalent to this yet?

For all Cubepilot and Mission Planner dev, this repository is the "upstream". I will make a PR to mavlink/mavlink upstream as well once this goes in, so IDs are reserved at the very least.

**Comment by bugobliterator** [comment]
From the error messages, cubepilot.xml doesn't seem to be the cause of failure though @peterbarker .

**Comment by peterbarker** [comment]
@bugobliterator rebase?

**Comment by bugobliterator** [comment]
> @bugobliterator rebase?

done

**Pull request merged**
