### PR TITLE
Pull in offboard-authorisation messages

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
closes https://github.com/ArduPilot/ardupilot/issues/6405

**Comment by magicrub** [comment]
blocks https://github.com/ArduPilot/ardupilot/pull/7315

**Comment by amilcarlucas** [comment]
Can this one please be made upstream ?

**Comment by peterbarker** [comment]
On Mon, 16 Apr 2018, Amilcar Lucas wrote:

> Can this one please be made upstream ?

Aren't the messages already upstream?  This PR was supposed to bring them 
into our fork.

**Comment by amilcarlucas** [comment]
Needs a rebase and the test must pass.

**Comment by amilcarlucas** [comment]
LGTM, but it needs a rebase and the test must pass.

**Comment by amilcarlucas** [comment]
@peterbarker @magicrub needs a rebase. We got a lot of merged commits from upstream now.

**Comment by amilcarlucas** [comment]
No need for this PR the cahnges are already in master

**Pull request closed without merging**
