### PR TITLE
common: add MAV_SYS_STATUS_SENSOR_PROXIMITY

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Can someone re-run travis ?

**Comment by rmackay9** [comment]
It would probably be good to merge this upstream as well (if possible) to stake out the bit so it doesn't get used by something else.

**Comment by amilcarlucas** [comment]
I already did one upstream PR yesterday, albeit not including this because the python 2.6 travis tests fail.

**Comment by OXINARF** [comment]
Yeah, as I said in https://github.com/ArduPilot/ardupilot/pull/6842#issuecomment-333147165, I think this should be submitted to upstream first because I'm afraid it can be rejected.

**Comment by amilcarlucas** [comment]
Yes Peter, can you please submit this one upstream ?

**Comment by amilcarlucas** [comment]
Ok, submitted upstream, closing it here. https://github.com/mavlink/mavlink/pull/889

**Pull request closed without merging**
