### PR TITLE
common.xml: add UTM_GLOBAL_POSITION message

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
So this is an old message which we don't support.

Doesn't conflict with our stuff, so we could probably pull it in to minimise changes.

OTOH, it could also be moved to a notional `px4.xml` instead as not even QGC understands it.

**Comment by amilcarlucas** [comment]
@hamishwillee can you comment on this?

**Comment by hamishwillee** [comment]
While I'd be the first to say "let's get everything in sync" it doesn't make sense to import this if no one is using it. So suggest hold off merging this.

I've added to the [20210203-Dev-Meeting](https://github.com/mavlink/mavlink/wiki/20210203-Dev-Meeting) for discussion and I'll try confirm the status of this one in the meantime.

**Comment by hamishwillee** [comment]
So this is used by PX4 in a similar way to ADSB messages: https://px4.slack.com/archives/C52DXKYLV/p1611205929003600

So you could reasonably merge, or wait and see if it needs to move - following dev call. Up to you.

**Comment by auturgy** [comment]
It seems like it sits in between the OpenDroneID and ADSB messages.  I'd suggest that we bring it in for now, although I hope it disappears when OpenDroneID is implemented.

**Review by tridge — APPROVED** [review]

**Pull request merged**
