### PR TITLE
Move MAV_CMD_DO_SPRAYER from ardupilotmega.xml to common.xml

### PR DESCRIPTION
**Pull request by amilcarlucas**
This way it can be globaly used.

### CODE REVIEW

**Comment by peterbarker** [comment]
Has the equivalent PR been made upstream?

**Comment by amilcarlucas** [comment]
yes

**Comment by peterbarker** [comment]
> yes

.... where is it?

**Comment by amilcarlucas** [comment]
https://github.com/mavlink/mavlink/pull/1585

**Comment by amilcarlucas** [comment]
I merged this one upstream. Can someone merge it here?

**Comment by peterbarker** [comment]
On Fri, 19 Feb 2021, Amilcar Lucas wrote:

> I merged this one upstream. Can someone merge it here?

Done, thanks.

**Pull request merged**
