### PR TITLE
common.xml: improve Radius description

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
So ArduPilot's sailing boats would violate this description.

@hamishwillee

**Comment by hamishwillee** [comment]
@peterbarker Thanks.  What this was trying to show was that an MC does not have a loiter radius/fly a circle - it just stops in place, so this does not apply to MC. How does loiter work for boats? 

Showing just the difference:

Original

> Radius around waypoint.

Proposed

> Loiter radius around waypoint for forward-only moving vehicles (not multicopters).

**Comment by peterbarker** [comment]
On Thu, 10 Dec 2020, Hamish Willee wrote:

> @peterbarker Thanks. What this was trying to show was that an MC does not have a loiter radius/fly a circle - it just stops in place, so this does not
> apply to MC. How does loiter work for boats?

Uses it for determining when to do stuff IIUC.  Only second-hand 
information here, I've only heard people talk about it.

https://www.youtube.com/watch?v=IBptvWRT_Tg

Sailboats get more extreme...

**Comment by hamishwillee** [comment]
Thanks. Agree, this not right. But nor is the old one for boats - since they don't loiter around the circle either. I think it is worth clarifying that this does not apply to all vehicles. How about:

> Radius around waypoint. Fixed wing vehicles loiter clockwise if the value is positive, otherwise counter-clockwise. This field is not used on MC vehicles (which hold position when loitering). Boats typically drift within the waypoint and correct position on breaching the circle defined by the radius.

**Comment by peterbarker** [comment]
I'm going to try to punt to our sailboat-type-person, @IamPete1 ...

**Review by tridge — APPROVED** [review]

**Pull request merged**
