### PR TITLE
BATTERY_STATUS.voltage_ext: add cells 10 to 14 (#1423)

### PR DESCRIPTION
**Pull request by amilcarlucas**
The required Ardupilot changes are in https://github.com/ArduPilot/ardupilot/pull/15404/commits/669e98bb6ba21d161036edca9bae7f5bfc43e026

and the CI tests pass

### CODE REVIEW

**Comment by magicrub** [comment]
is this from upstream?

**Comment by amilcarlucas** [comment]
yes, it is

**Comment by amilcarlucas** [comment]
All tests pass, can this be reviewd?

**Comment by amilcarlucas** [comment]
@WickedShell can you please review this?

**Review by tridge — APPROVED** [review]

**Pull request merged**
