### PR TITLE
Message Definitions ardupilotmega.xml

### PR DESCRIPTION
**Pull request by robinhilliard**
Added display="bitmask" to EKF_STATUS_REPORT flags field, as related enum values seem to be for a bitmask. Raised on mavlink mailing list and Hamish asked me to create a PR.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
I can not merge this one on this repo. Can you do an upstream PR to mavlink/mavlink ?

**Comment by auturgy** [comment]
Robin was told by upstream to contribute the patch here, as it’s on Ardupilotmega

**Comment by robinhilliard** [comment]
> I can not merge this one on this repo. Can you do an upstream PR to mavlink/mavlink ?

Given @auturgy's response do I still need to do another PR?

**Comment by auturgy** [comment]
@tridge 
Some preliminary discussion with Hamish on the mavlink mailing list

**Comment by robinhilliard** [comment]
BTW I just noticed the same applies to common.xml camera_information camera_cap_flags - should I add to this PR?

**Comment by auturgy** [comment]
It’s probably better to put that one upstream 

Regards,

James

**Comment by amilcarlucas** [comment]
@tridge can you merge this small one?

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
