### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by amilcarlucas**
Copter builds fine with these changes

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Tests pass, and it builds copter fine, can this be merged ?

**Comment by amilcarlucas** [comment]
`
IOError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pymavlink-2.3.7-py2.7-linux-x86_64.egg/pymavlink/generator/java/lib/messages/MAVLinkMessage.java'
The command "mavgen.py --lang='Java'       --output=/tmp/mavgen_test mavlink/message_definitions/v1.0/common.xml --wire-protocol=1.0 --strict-units" exited with 1.
`
Travis chokes on this :(

**Comment by tridge** [comment]
PR for this against ardupilot here:
https://github.com/ArduPilot/ardupilot/pull/11611

**Comment by amilcarlucas** [comment]
Thanks @tridge

**Pull request closed without merging**
