### PR TITLE
common.xml: added MAV_CMD_BATTERY_RESET

### PR DESCRIPTION
**Pull request by tridge**
allows for batteries to be reset on battery swap

### CODE REVIEW

**Comment by WickedShell** [comment]
Absolutely needs to be indexed, or have a flag for all.

**Comment by tridge** [comment]
@WickedShell that is what param1 is for (battery mask)

**Comment by OXINARF** [comment]
Since this is in common, it should be proposed upstream.

**Comment by tridge** [comment]
@OXINARF I'm not going to wait for upstream merge lag.

**Pull request merged**
