### PR TITLE
Add FENCE_ACTION_GUIDED_THROUGH_HOME enum

### PR DESCRIPTION
**Pull request by magicrub**
Switch to guided mode and travel to a point on the other side of the fence with a heading that takes you through home. This is similar to FENCE_ACTION_RTL except it just keeps going and at the current altitude and will eventually hit the fence again and again flying over/through home each time

### CODE REVIEW

**Comment by magicrub** [comment]
this blocks https://github.com/ArduPilot/ardupilot/pull/7263

**Comment by lvale** [comment]
so, is a fence or not ? or is a wire mesh fence ?

**Comment by amilcarlucas** [comment]
Can someone re-run travis ?

**Comment by WickedShell** [comment]
Until we decide if the PR this is for is moving forward I wouldn't merge this. There is some confusion on what the feature is actually doing.

**Comment by auturgy** [comment]
Should this be closed?

**Pull request closed without merging**
