### PR TITLE
Copter mode

### PR DESCRIPTION
**Pull request by amilcarlucas**
Requires #88

### CODE REVIEW

**Comment by rmackay9** [comment]
I don't think we should add in POSITION or OF_LOITER modes.  Those are very old and were never popular so they've been removed.

**Comment by amilcarlucas** [comment]
Good points I was not sure about those, that is why I did separated PRs.

**Comment by amilcarlucas** [comment]
So I should only use COPTER_MODE_FLOWHOLD in the second commit?

**Comment by rmackay9** [comment]
@amilcarlucas, yes, just FLOWHOLD in the 2nd commit would be good I think.

**Comment by WickedShell** [comment]
This is MAVLink rather then something user facing, if the mode ever shipped
then it should be in this list I think... Shouldn't descriptions actually
describe the flight move rather then be an almost exact match for the enum
name?

**Comment by amilcarlucas** [comment]
I plan to remove some redundant code from pymavlink/mavutil.py:1649 until 1727
For that I need these descriptions. And hence the comment on top of each enum.

**Comment by WickedShell** [comment]
In my opinion the enum is still better mapping out to a description of the flight mode, the way other enums also map out to useful descriptions.

**Comment by rmackay9** [comment]
I actually don't think those old modes should be in there.  All it will really lead to is "what is OF_LOITER?" and "What is Position mode?" and "why can't I change into OF_LOITER or POSITION mode from ROS?".

I understand what you're saying @WickedShell but in practice it won't help.

**Comment by amilcarlucas** [comment]
Closed in favor of ArduPilot/pymavlink#468

**Pull request closed without merging**
