### PR TITLE
Deprecate MAV_DATA_STREAM

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
I know this is coming from upstream - but it's a bit weird, really.

Know that I don't *like* data streams, but from a practical perspective, all GCSs use them *and* they'yre much easier to deal with on the autopilot that message intervals.

I still think they should die, but I'm not sure we know how to kill them yet, at least on the ArduPilot side of things....

**Comment by amilcarlucas** [comment]
This does not kill them, this just signals the users that it will get killed at some point.

**Comment by tridge** [comment]
we can't deprecate streams until we had a valid replacement

**Comment by amilcarlucas** [comment]
Grouping of new (non discoverable) messages is not possible with SET_MEASSAGE_INTERVAL so this can not be deprecated

**Pull request closed without merging**
