### PR TITLE
20190924 upstream changes

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Added more upstream changes.

**Comment by IamPete1** [comment]
@amilcarlucas @tridge we seem to have lost https://github.com/ArduPilot/mavlink/pull/108 somewhere, it was included in this at one point.

**Comment by amilcarlucas** [comment]
@IamPete1 sorry. I had it in, but then I realised it was WIP, and we have a policy of not merging WIP into our stable mavlink fork. So I had to remove it.

**Comment by IamPete1** [comment]
@amilcarlucas I thought I was doing it in the right order getting the new feature into mavlink first? I have the ArduPilot implementation to use this new extension waiting in a branch.

**Comment by amilcarlucas** [comment]
the best is to reopen #108 and do an ardupilot PR with a reference to the #108

**Comment by IamPete1** [comment]
OK, will do, Thanks, Have I done it correctly or would there have been a better way? I have https://github.com/mavlink/mavlink/pull/1228 coming soon also hopefully. Maybe I should have done the PR here first and pulled into mavlink rather than the other way?

**Comment by amilcarlucas** [comment]
You did it correctly. I was the one that failed to explain you the workflow for WIP messages.

**Comment by IamPete1** [comment]
Thank You!

**Pull request merged**
