### PR TITLE
common.xml: add MAV_MOUNT_MODE_HOME_LOCATION to point at home

### PR DESCRIPTION
**Pull request by peterbarker**
@amilcarlucas @hamishwillee Thoughts?

### CODE REVIEW

**Comment by auturgy** [comment]
Changes to common.xml need to go via mavlink/mavlink else we diverge.

**Comment by amilcarlucas** [comment]
Looks good to me but needs to be done upstream first.

**Comment by peterbarker** [comment]
> Changes to common.xml need to go via mavlink/mavlink else we diverge.

I realise that.  But it needs to go into our repo as a branch first so the PR showing an implementation pass.  Doesn't need to be a PR, but it allows for easier commenting.  Perhaps I should've tagged it....

There's not a lot of point making a PR upstream (and likely having it instantly merged!) if we don't have agreement about the utility of the feature ourselves.

**Comment by peterbarker** [comment]
Upstream PR is here: https://github.com/mavlink/mavlink/pull/1546

Reception for the feature into ArduPilot was positive.

**Comment by peterbarker** [comment]
Merging this as upstream was merged.

**Pull request merged**
